name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2


      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload a Build Artifact
  uses: actions/upload-artifact@v3.1.2

        with:
          name: app-debug.apk  
          path: app/build/outputs/apk/debug/app-debug.apk
